//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paper()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int PaperID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<bool> Active { get; set; }
        public string FilenameOriginal { get; set; }
        public string Filename { get; set; }
        public string Title { get; set; }
        public string Certification { get; set; }
        public string NotesToReviewers { get; set; }
        public Nullable<bool> AnalysisOfAlgorithms { get; set; }
        public Nullable<bool> Applications { get; set; }
        public Nullable<bool> Architecture { get; set; }
        public Nullable<bool> ArtificialIntelligence { get; set; }
        public Nullable<bool> ComputerEngineering { get; set; }
        public Nullable<bool> Curriculum { get; set; }
        public Nullable<bool> DataStructures { get; set; }
        public Nullable<bool> Databases { get; set; }
        public Nullable<bool> DistanceLearning { get; set; }
        public Nullable<bool> DistributedSystems { get; set; }
        public Nullable<bool> EthicalSocietalIssues { get; set; }
        public Nullable<bool> FirstYearComputing { get; set; }
        public Nullable<bool> GenderIssues { get; set; }
        public Nullable<bool> GrantWriting { get; set; }
        public Nullable<bool> GraphicsImageProcessing { get; set; }
        public Nullable<bool> HumanComputerInteraction { get; set; }
        public Nullable<bool> LaboratoryEnvironments { get; set; }
        public Nullable<bool> Literacy { get; set; }
        public Nullable<bool> MathematicsInComputing { get; set; }
        public Nullable<bool> Multimedia { get; set; }
        public Nullable<bool> NetworkingDataCommunications { get; set; }
        public Nullable<bool> NonMajorCourses { get; set; }
        public Nullable<bool> ObjectOrientedIssues { get; set; }
        public Nullable<bool> OperatingSystems { get; set; }
        public Nullable<bool> ParallelsProcessing { get; set; }
        public Nullable<bool> Pedagogy { get; set; }
        public Nullable<bool> ProgrammingLanguages { get; set; }
        public Nullable<bool> Research { get; set; }
        public Nullable<bool> Security { get; set; }
        public Nullable<bool> SoftwareEngineering { get; set; }
        public Nullable<bool> SystemsAnalysisAndDesign { get; set; }
        public Nullable<bool> UsingTechnologyInTheClassroom { get; set; }
        public bool WebAndInternetProgramming { get; set; }
        public Nullable<bool> Other { get; set; }
        public string OtherDescription { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
