//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewID { get; set; }
        public Nullable<int> PaperID { get; set; }
        public Nullable<int> ReviewerID { get; set; }
        public Nullable<decimal> AppropriatenessOfTopic { get; set; }
        public Nullable<decimal> TimelinessOfTopic { get; set; }
        public Nullable<decimal> SupportiveEvidence { get; set; }
        public Nullable<decimal> TechnicalQuality { get; set; }
        public Nullable<decimal> ScopeOfCoverage { get; set; }
        public Nullable<decimal> CitationOfPreviousWork { get; set; }
        public Nullable<decimal> Originality { get; set; }
        public string ContentComments { get; set; }
        public Nullable<decimal> OrganizationOfPaper { get; set; }
        public Nullable<decimal> ClarityOfMainMessage { get; set; }
        public Nullable<decimal> Mechanics { get; set; }
        public string WrittenDocumentComments { get; set; }
        public Nullable<decimal> SuitabilityForPresentation { get; set; }
        public Nullable<decimal> PotentialInterestInTopic { get; set; }
        public string PotentialForOralPresentationComments { get; set; }
        public Nullable<decimal> OverallRating { get; set; }
        public string OverallRatingComments { get; set; }
        public Nullable<decimal> ComfortLevelTopic { get; set; }
        public Nullable<decimal> ComfortLevelAcceptability { get; set; }
        public Nullable<bool> Complete { get; set; }
    
        public virtual Paper Paper { get; set; }
        public virtual Reviewer Reviewer { get; set; }
    }
}
